CREATE TABLE IF NOT EXISTS users(
	u_id VARCHAR(36) PRIMARY KEY UNIQUE NOT NULL,
	username TEXT UNIQUE NOT NULL,
    email TEXT,
	password VARCHAR(100),
	p_id VARCHAR(36) NOT NULL,
	overwatcher BOOLEAN DEFAULT 0 NOT NULL,
	active BOOLEAN DEFAULT 1 NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS user_search ON users (username, email);

CREATE TABLE IF NOT EXISTS messages(
	id VARCHAR(36) PRIMARY KEY NOT NULL,
	sender VARCHAR(36),
	reciever VARCHAR(36),
	message VARCHAR(10000) NOT NULL,
	stamped TIMESTAMP NOT NULL,
	FOREIGN KEY (sender) REFERENCES users(id),
	FOREIGN KEY (reciever) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS message_id ON messages (id),
CREATE INDEX IF NOT EXISTS message_content ON messages (message),
CREATE INDEX IF NOT EXISTS message_conversation ON messages (sender, reciever);